import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ClashDisplay = localFont({
  src: [
    {
      path: './font/ClashDisplay/ClashDisplay-Extralight.otf',
      weight: '100',
      
    },
    {
      path: './font/ClashDisplay/ClashDisplay-Light.otf',
      weight: '200',
    },
    {
      path: './font/ClashDisplay/ClashDisplay-Regular.otf',
      weight: '300',
    },
    {
      path: './font/ClashDisplay/ClashDisplay-Medium.otf',
      weight: '400',
    },
    {
      path: './font/ClashDisplay/ClashDisplay-Semibold.otf',
      weight: '500',
    },
    {
      path: './font/ClashDisplay/ClashDisplay-Bold.otf',
      weight: '600',
    },
  ],
    variable: '--font-clash-display',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ClashDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
